# Generated by Django 3.0.8 on 2020-08-12 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import muglaSepetiApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path)),
                ('slug', models.SlugField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email address must be entered in the format: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')])),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('tripadvisor', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='isim')),
                ('detail', models.CharField(max_length=100, verbose_name='ürün detayı')),
                ('price', models.FloatField(verbose_name='fiyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='kapak fotoğrafı')),
            ],
            options={
                'verbose_name': 'Menü Ürünü',
                'verbose_name_plural': 'Menü Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email address must be entered in the format: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')])),
                ('address', models.ManyToManyField(to='muglaSepetiApp.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entry_list', models.ManyToManyField(to='muglaSepetiApp.Entry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='isim')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sahip')),
            ],
            options={
                'verbose_name': 'Menü Grubu',
                'verbose_name_plural': 'Menü Grupları',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='isim')),
                ('image', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='kapak fotoğrafı')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.FoodGroup', verbose_name='grup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sahip')),
            ],
            options={
                'verbose_name': 'Menü Kategorisi',
                'verbose_name_plural': 'Menü Kategorileri',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.FoodCategory', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_entry', to='muglaSepetiApp.Company', verbose_name='sirket'),
        ),
        migrations.AddField(
            model_name='company',
            name='active_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Menu'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BucketEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(max_length=500)),
                ('order_phone', models.CharField(max_length=500)),
                ('delivered_at', models.DateTimeField()),
                ('checked_at', models.DateTimeField()),
                ('ordered_at', models.DateTimeField()),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('N', 'Nakit'), ('K', 'Kredi Kartı')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Company')),
                ('order_list', models.ManyToManyField(blank=True, to='muglaSepetiApp.BucketEntry')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Profile')),
            ],
        ),
    ]
