# Generated by Django 3.0.8 on 2020-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='if this box is checked your company status will be changed to busy which mean you might not be able to send packet to buyer on right time', verbose_name='is Busy'),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='if your product is out of stack select this option to hide from products', verbose_name='Hide product'),
        ),
    ]
