# Generated by Django 3.0.8 on 2020-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0002_auto_20201005_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('message', models.CharField(max_length=250, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='is annoucment active')),
            ],
        ),
    ]
