# Generated by Django 3.0.8 on 2020-08-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0002_auto_20200812_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='muglaSepetiApp.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(related_name='profile_address', to='muglaSepetiApp.Address'),
        ),
    ]
