# Generated by Django 3.0.8 on 2020-10-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0003_annoucment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CollationNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_already_added', models.BooleanField(default=False, verbose_name='is this material already in your food menu price')),
                ('collation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Collation')),
            ],
        ),
        migrations.CreateModel(
            name='CollationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('collation_list', models.ManyToManyField(to='muglaSepetiApp.CollationNode')),
            ],
        ),
    ]
