# Generated by Django 3.0.8 on 2020-08-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0004_auto_20200812_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
