# Generated by Django 3.0.8 on 2020-08-13 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0006_auto_20200813_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='closed_at',
        ),
        migrations.AddField(
            model_name='bucket',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='bucket',
            name='is_on_the_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucket',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='close_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='open_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
