# Generated by Django 3.0.8 on 2020-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0006_auto_20201007_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketcollation',
            name='collation',
        ),
        migrations.AlterField(
            model_name='bucketcollation',
            name='collation_list',
            field=models.ManyToManyField(null=True, to='muglaSepetiApp.CollationNode', verbose_name='Collation List'),
        ),
    ]
