# Generated by Django 3.0.8 on 2020-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0007_auto_20201017_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketcollation',
            name='collation_list',
            field=models.ManyToManyField(blank=True, to='muglaSepetiApp.CollationNode', verbose_name='Collation List'),
        ),
    ]
