# Generated by Django 3.0.8 on 2020-08-13 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0008_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='sahip'),
        ),
    ]
