# Generated by Django 3.0.8 on 2020-10-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0009_auto_20201018_0736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collationnode',
            unique_together={('collation', 'is_already_added')},
        ),
    ]
