# Generated by Django 3.0.8 on 2020-10-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0010_auto_20201018_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collationlist',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='name'),
        ),
    ]
