# Generated by Django 3.0.8 on 2020-08-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0010_auto_20200813_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='owner',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='foodgroup',
            old_name='owner',
            new_name='company',
        ),
    ]
