# Generated by Django 3.0.8 on 2020-10-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0011_auto_20201018_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='collation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='collationlist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='collationnode',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='collation',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='collationlist',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='collation',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='collationlist',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='collationnode',
            unique_together={('collation', 'is_already_added', 'company')},
        ),
    ]
