# Generated by Django 3.0.8 on 2020-08-14 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0011_auto_20200814_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='owner',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='active_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_active_menu', to='muglaSepetiApp.Menu'),
        ),
    ]
