# Generated by Django 3.0.8 on 2020-10-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0012_auto_20201018_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='cancel note'),
        ),
    ]
