# Generated by Django 3.0.8 on 2020-08-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0012_auto_20200814_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
