# Generated by Django 3.0.8 on 2020-08-17 02:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muglaSepetiApp', '0005_auto_20200812_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adress', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='bucket',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='bucketentry',
            options={'verbose_name': 'Bucket Product', 'verbose_name_plural': 'Bucket Products'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=500, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='muglaSepetiApp.Profile', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check time'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancel time'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deliver time'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='delivery note'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='is checked'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, verbose_name='is delivered'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='is_on_the_way',
            field=models.BooleanField(default=False, verbose_name='is on the way'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='is ordered'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='on the way time'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='order_address',
            field=models.CharField(max_length=500, verbose_name='order address'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='order_list',
            field=models.ManyToManyField(blank=True, to='muglaSepetiApp.BucketEntry', verbose_name='order list'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='order_phone',
            field=models.CharField(max_length=500, verbose_name="orderer's phone"),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='order time'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='payment_type',
            field=models.CharField(choices=[('N', 'Cash'), ('K', 'Credit Card')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Profile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='bucketentry',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='bucketentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Entry', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='bucketentry',
            name='price',
            field=models.FloatField(default=0, verbose_name='Total Bucket Price'),
        ),
        migrations.AlterField(
            model_name='company',
            name='active_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_active_menu', to='muglaSepetiApp.Menu', verbose_name='active menu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=500, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='close_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email adresi doğru formatta girilmeli: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')], verbose_name='email adress'),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='instagram address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_open',
            field=models.BooleanField(default=False, help_text='if this box not checked your company wont open even if it currently open-hours', verbose_name='is Open'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='open_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='open time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası doğru formatta girilmeli: '+999999999'. 15 karakter limiti vardır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pinterest',
            field=models.URLField(blank=True, verbose_name='pinterest address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tripadvisor',
            field=models.URLField(blank=True, verbose_name='tripadvisor address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='twitter address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='youtube address'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.FoodCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_entry', to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='detail',
            field=models.CharField(max_length=100, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.FoodGroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='entry_list',
            field=models.ManyToManyField(to='muglaSepetiApp.Entry', verbose_name='Entry list'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(related_name='profile_address', to='muglaSepetiApp.Address', verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email adresi doğru formatta girilmeli: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası doğru formatta girilmeli: '+999999999'. 15 karakter limiti vardır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
