# Generated by Django 3.0.8 on 2020-08-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0015_auto_20200817_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='bucket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Bucket', verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
