# Generated by Django 3.0.8 on 2020-09-20 16:20

from django.db import migrations, models
import django.db.models.deletion
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0021_auto_20200920_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderTitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Slider Title')),
                ('sliderDescription', models.CharField(blank=True, max_length=20, null=True, verbose_name='Slider Description')),
                ('sliderImage1', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Slider Image 1')),
                ('sliderImage2', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Slider Image 2')),
                ('sliderImage3', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Slider Image 3')),
                ('sliderImage4', models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Slider Image 4')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Config', verbose_name='Site Config')),
            ],
        ),
    ]
