# Generated by Django 3.0.8 on 2020-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0022_config_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='sliderDescription',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Description'),
        ),
    ]
