# Generated by Django 3.0.8 on 2020-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0023_auto_20200920_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='Muğla Config', max_length=20),
            preserve_default=False,
        ),
    ]
