# Generated by Django 3.0.8 on 2020-09-20 16:35

from django.db import migrations, models
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0024_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Site Logo'),
        ),
    ]
