# Generated by Django 3.0.8 on 2020-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0025_config_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='contentDescription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='config',
            name='siteDescription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Site Description'),
        ),
    ]
