# Generated by Django 3.0.8 on 2020-09-20 18:06

from django.db import migrations, models
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0026_auto_20200920_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Site Logo'),
        ),
        migrations.AddField(
            model_name='config',
            name='googleplus',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
