# Generated by Django 3.0.8 on 2020-09-20 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0027_auto_20200920_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='address',
            field=models.CharField(default=905076239641, max_length=100, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email adresi doğru formatta girilmeli: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')], verbose_name='email adress'),
        ),
        migrations.AddField(
            model_name='config',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası doğru formatta girilmeli: '+999999999'. 15 karakter limiti vardır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
