# Generated by Django 3.0.8 on 2020-09-20 21:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0028_auto_20200920_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='config',
            name='breadcrumbBackground',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Breadcrumb Background'),
        ),
        migrations.AddField(
            model_name='config',
            name='menuBackground',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Menu Background'),
        ),
        migrations.AddField(
            model_name='config',
            name='menuInnerBackground',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Menu Inner Background'),
        ),
        migrations.AlterField(
            model_name='config',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='config',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email adresi doğru formatta girilmeli: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='muglaSepetiApp.Address', verbose_name='address'),
        ),
    ]
