# Generated by Django 3.0.8 on 2020-09-20 22:46

from django.db import migrations, models
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0030_auto_20200921_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='breadcrumbBackground',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Breadcrumb Background'),
        ),
    ]
