# Generated by Django 3.0.8 on 2020-09-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0032_auto_20200921_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='aboutus_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
