# Generated by Django 3.0.8 on 2020-09-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0033_auto_20200921_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='aboutus_description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
