# Generated by Django 3.0.8 on 2020-09-21 01:07

import django.core.validators
from django.db import migrations, models
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0039_auto_20200921_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='order_background',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='Order Background'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_title_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 1'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_title_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 2'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_title_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 3'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_title_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 4'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_value_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 1'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_value_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 1'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_value_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 1'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_fact_value_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 1'),
        ),
    ]
