# Generated by Django 3.0.8 on 2020-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0041_auto_20200923_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='mail_after_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='password reset text end'),
        ),
        migrations.AddField(
            model_name='config',
            name='mail_before_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='password reset text head'),
        ),
    ]
