# Generated by Django 3.0.8 on 2020-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0042_auto_20200923_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='mail_after_text',
        ),
        migrations.RemoveField(
            model_name='config',
            name='mail_before_text',
        ),
    ]
