# Generated by Django 3.0.8 on 2020-08-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Menu'),
        ),
    ]
