# Generated by Django 3.0.8 on 2020-08-17 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muglaSepetiApp', '0014_auto_20200817_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'Beğenmedim'), ('2', 'İdare eder'), ('3', 'İyiydi işte'), ('4', 'Güzeldi'), ('5', 'Mükemmeldi')], max_length=1)),
                ('comment', models.CharField(max_length=100, verbose_name='comment')),
                ('time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='bucket',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Comment', verbose_name='Comment'),
        ),
    ]
