# Generated by Django 3.0.8 on 2020-09-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0017_auto_20200826_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='muglaSepetiApp.Profile', verbose_name='profile'),
        ),
    ]
