# Generated by Django 3.0.8 on 2020-10-05 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0025_config_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sliderDescription',
            new_name='slider_description',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sliderImage1',
            new_name='slider_image_1',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sliderImage2',
            new_name='slider_image_2',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sliderImage3',
            new_name='slider_image_3',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sliderImage4',
            new_name='slider_image_4',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='sliderTitle',
            new_name='slider_title',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='foodgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='owner',
        ),
        migrations.AddField(
            model_name='bucket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancel time'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='delivery note'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='is_on_the_way',
            field=models.BooleanField(default=False, verbose_name='is on the way'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='on the way time'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='new adress', max_length=500, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='close_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='close time'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='if this box is checked your company status will be changed to busy which mean you might not be able to send packet to buyer on right time', verbose_name='is Busy'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_open',
            field=models.BooleanField(default=False, help_text='if this box not checked your company wont open even if it currently open-hours', verbose_name='is Open'),
        ),
        migrations.AddField(
            model_name='company',
            name='open_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='open time'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_delay',
            field=models.DurationField(default=30, verbose_name='Service Delay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='about_background_quotes',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Quotes Background '),
        ),
        migrations.AddField(
            model_name='config',
            name='about_content_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_content_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Content Title'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic Title 4'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistic Value 4'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_image_large',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image Large'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_1',
            field=models.CharField(blank=True, help_text="Type writer name end of the text heading with '-' Ex:-Furkankykc", max_length=300, null=True, verbose_name='Quote 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_2',
            field=models.CharField(blank=True, help_text="Type writer name end of the text heading with '-' Ex:-Furkankykc", max_length=300, null=True, verbose_name='Quote 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_3',
            field=models.CharField(blank=True, help_text="Type writer name end of the text heading with '-' Ex:-Furkankykc", max_length=300, null=True, verbose_name='Quote 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quotes Title'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='config',
            name='bread_crumb_background',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Breadcrumb Background'),
        ),
        migrations.AddField(
            model_name='config',
            name='content_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='config',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Email adresi doğru formatta girilmeli: 'example@mail.com'.", regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')], verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='config',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])], verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='config',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='config',
            name='googleplus',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='menu_background',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='Menu Background'),
        ),
        migrations.AddField(
            model_name='config',
            name='menu_inner_background',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='Menu Inner Background'),
        ),
        migrations.AddField(
            model_name='config',
            name='order_background',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='Order Background'),
        ),
        migrations.AddField(
            model_name='config',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası doğru formatta girilmeli: '+999999999'. 15 karakter limiti vardır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='config',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='site_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Site Description'),
        ),
        migrations.AddField(
            model_name='config',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='if your product is out of stack select this option to hide from products', verbose_name='Hide product'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muglaSepetiApp.Company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='menu',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muglaSepetiApp.Company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='muglaSepetiApp.Address', verbose_name='address'),
        ),
    ]
