# Generated by Django 3.0.8 on 2020-09-20 23:28

from django.db import migrations, models
import muglaSepetiApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0035_auto_20200921_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='about_background_quotes',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Quotes Background '),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_title_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Statistic 4'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='about_fact_value_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='about_image_large',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image Large'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_description_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Information Description 4'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_info_title_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Information Title 4'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_1',
            field=models.CharField(blank=True, help_text="Type writer name end of the text heading with '-' Ex:-Furkankykc", max_length=300, null=True, verbose_name='Quote 1'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_2',
            field=models.CharField(blank=True, help_text="Type writer name end of the text heading with '-' Ex:-Furkankykc", max_length=300, null=True, verbose_name='Quote 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_3',
            field=models.CharField(blank=True, help_text="Type writer name end of the text heading with '-' Ex:-Furkankykc", max_length=300, null=True, verbose_name='Quote 3'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_quote_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quotes Title'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image 1'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image 2'),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=muglaSepetiApp.models.get_image_path, verbose_name='About Image 3'),
        ),
    ]
