# Generated by Django 3.0.8 on 2020-09-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0036_auto_20200921_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='about_info_description_4',
        ),
        migrations.RemoveField(
            model_name='config',
            name='about_info_title_4',
        ),
    ]
