# Generated by Django 3.0.8 on 2020-09-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muglaSepetiApp', '0037_auto_20200921_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='about_content_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content Title'),
        ),
        migrations.AddField(
            model_name='config',
            name='about_content_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Content Title'),
        ),
    ]
