"""
Django settings for muglaSepeti project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j_0!f=(^3mx8^3t1x%(q^1%^h&2z*s*!u=^b)@sj@j9n157i42'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'liststyle',
    'admin_reorder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'muglaSepetiApp.apps.MuglasepetiappConfig',
    'django.contrib.humanize',
    'django.forms',
]

MIDDLEWARE = [

    'admin_reorder.middleware.ModelAdminReorder',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'muglaSepeti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'muglaSepetiApp.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'muglaSepeti.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
ADMIN_REORDER = (
    # Keep original label and models
    'sites',
    # models with custom name
    {'app': 'muglaSepetiApp', 'models': ({'model': 'muglaSepetiApp.Bucket', 'label': 'Sipariş Paneli'},
                                         )
     },
    {'app': 'auth', 'models': ('auth.User', 'auth.Group')},
    # Rename app
    {'app': 'muglaSepetiApp', 'models': (
        'muglaSepetiApp.Company', 'muglaSepetiApp.FoodGroup', 'muglaSepetiApp.FoodCategory', 'muglaSepetiApp.Entry',
        'muglaSepetiApp.Menu', 'muglaSepetiApp.Comment', 'muglaSepetiApp.Profile', 'muglaSepetiApp.Address',
        'muglaSepetiApp.PacketPrice', 'muglaSepetiApp.SiteConfig', 'muglaSepetiApp.Config'),
     'label': 'Muğla Sepeti | Düzenle'},

)
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

# Mail sending

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'furkanfbr@gmail.com'
EMAIL_HOST_PASSWORD = 'rghzpghdhchyqkaa'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'Muğla Sepeti Ekibi <noreply@muglasepeti.com>'
USE_TZ = True
LOCALE_PATHS = ('static/locale',)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join('static'),)
# STATIC_ROOT = ""
LOGIN_REDIRECT_URL = 'home'
